# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RedShiftCluster(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, cluster_id: str=None):  # noqa: E501
        """RedShiftCluster - a model defined in Swagger

        :param cluster_id: The cluster_id of this RedShiftCluster.  # noqa: E501
        :type cluster_id: str
        """
        self.swagger_types = {
            'cluster_id': str
        }

        self.attribute_map = {
            'cluster_id': 'clusterId'
        }

        self._cluster_id = cluster_id

    @classmethod
    def from_dict(cls, dikt) -> 'RedShiftCluster':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RedShiftCluster of this RedShiftCluster.  # noqa: E501
        :rtype: RedShiftCluster
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cluster_id(self) -> str:
        """Gets the cluster_id of this RedShiftCluster.


        :return: The cluster_id of this RedShiftCluster.
        :rtype: str
        """
        return self._cluster_id

    @cluster_id.setter
    def cluster_id(self, cluster_id: str):
        """Sets the cluster_id of this RedShiftCluster.


        :param cluster_id: The cluster_id of this RedShiftCluster.
        :type cluster_id: str
        """
        if cluster_id is None:
            raise ValueError("Invalid value for `cluster_id`, must not be `None`")  # noqa: E501

        self._cluster_id = cluster_id
